# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-24T19:51:32+00:00
# Github: haniyeka

name: MURaM_Build_cpu_container_fftwheffte

on:
  #schedule:
    #runs the workflow every Monday at midnight.
    #- cron: '0 0 * * MON' 
  push:
    branches:
      - main
    paths: 
      - ./
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
    
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: haniyeka/carl_fftw_heffte:1.0
    steps:
    - name: Set environmental variables
      run: | 
        echo "MURaM_HOME_DIR=$(pwd)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Ensure FFTW and HEFFTE Installation
      run: |
        echo $FFTW3_HOME
        echo $HEFFTE_HOME
        echo $CUDA_HOME
    - name: Removing the Path References in Make_defs File
      run: |
        echo "replace the suitable make_def for casper..." 
        cp casper/Make_defs_casper ./Make_defs
        echo "see the paths inside: "
        head -n 10 Make_defs
        
        echo "correct the path ..."
        while IFS= read -r line; do
          if [[ $line == MURaM_HOME_DIR* ]]; then
            echo -e ""
          elif [[ $line == FFTW3_HOME* ]]; then
            echo -e ""
          elif [[ $line == HEFFTE_HOME* ]]; then
            echo -e ""
          elif [[ $line == CUDA_HOME* ]]; then
            echo -e ""
          else
            echo -e "$line"
          fi
        done < Make_defs > temp_file && mv temp_file Make_defs
        
        echo "see new paths inside: "
        #head -n 10 Make_defs
        cat Make_defs
    - name: Build Muram
      run: |
        # The image is obtained from Carl's docker container. 
        # singularity remote login -u $user -p glpat-BSwDmLUnv8KzyQx1hNvA docker://registry.gitlab.com/cponder
        # singularity pull docker://registry.gitlab.com/cponder/containers/ubuntu-pgi-openmpi/selene:latest
        # the image is large in size and you'll need to allocate about 120GB of memory when pulling the image.  
        echo $IMAGE_PATH
        module load singularity
        singularity exec --nv --bind /glade:/glade $IMAGE_PATH /bin/bash -c 'make clean && make'
    - name: Check build
      run: |
        module load singularity
        singularity exec --nv --bind /glade:/glade $IMAGE_PATH /bin/bash -c 'ls ./src/mhd3d.x'
    - name: Verify GPU and CPU Results
      run: | 
        cp ./src/mhd3d.x ./TEST/Test_3D
        #change the parameters 
        #submit the job or run the script
