# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-24T19:51:32+00:00
# Github: haniyeka

name: specific_commit

on:
  schedule:
    #runs the workflow every Monday at midnight.
    #- cron: '0 0 * * MON' 
  push:
    branches:
      - main
    paths: 
      - ./
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 28222cff1015d76dba6ead5a871face4a10f7a5b
    - name: cat file 
      run: |
        cat .github/workflows/MURaM_build.yaml
  
      
      
      
      
      
      
      
