# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-24T19:51:32+00:00
# Github: haniyeka

version: 2.1
executors:
  executor:
    docker:
      - image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
workflows:
  build-and-test:
    jobs:
      - build-and-test-CMake-matrixMult-FORTRAN
      - build-and-test-Makefile-matrixMult-FORTRAN
      - build-and-test-Autoconfig-matrixMult-FORTRAN
jobs:
  build-and-test-CMake-matrixMult-FORTRAN:
    executor: executor
    steps:
      - checkout
      - run: 
          name: Check directory and build
          command: |
            cd CMake/matrixMult/FORTRAN/ && pwd && mkdir buil
            mkdir build 
            cd build && cmake ..
            make
            echo Test && ./matrix_mult
          
  build-and-test-Makefile-matrixMult-FORTRAN:
    executor: executor
    steps:
      - checkout
      - run:
          name: Check directory and build
          command: |
            cd Makefile/matrixMult/FORTRAN/ && pwd
            make
            echo Test && ./matrix_mult
            
  build-and-test-Autoconfig-matrixMult-FORTRAN:
    executor: executor
    steps:
      - checkout
      - run:
          name: Check directory and build
          command: |
            cd Autoconfig/matrixMult/FORTRAN/ 
            pwd && autoconf
            ./configure && make
            echo Test && ./matrix_mult
