# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-24T19:51:32+00:00
# Github: haniyeka

name: clubb_casper_cpu

on:
  schedule:
    - cron: '0 0 1 * *' #Runs once a month
    # - cron: '0 0 * * MON' #Runs once a week
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - uses: actions/checkout@v3
    
    - name: Ensure we are not in login mode
      run: |
        # on caster or any pbs system, $PBS_ENVIRONMENT will give some informations about the job
        if [[ $PBS_ENVIRONMENT != "PBS_INTERACTIVE" && $PBS_ENVIRONMENT != "PBS_BATCH" ]]; then
          echo "::error::Workflow is running in login mode"
          exit 1
        else
          echo "Workflow is running in $PBS_ENVIRONMENT mode!"
          echo JobID = $PBS_JOBID
        fi    

    - name: Navigate to directory and build with make
      run: |
        echo $LD_LIBRARY_PATH
        echo $GFORTRAN_NETCDF_FORTRAN
        echo "Current directory:" 
        echo $(pwd)
        module purge
        module load intel
        module load netcdf
        module load ncarenv
        module load ncarcompilers
        module load mkl
        module list
        pwd
        cd ./compile/
        echo "Test build:"
        ./compile.bash -c ./config/linux_x86_64_ifort.bash
        echo "Build successful"
    
    - name: Run Tests
      run: |
        echo "Running tests"
        cd ../run_scripts/
        ./run_scm_all.bash
        echo "Every test passed successfully."

