# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-26T15:21:21+00:00
# Github: haniyeka

name: mpas_casper_cpu

on:
  schedule:
    - cron: '0 0 1 * *' #Runs once a month
    # - cron: '0 0 * * MON' #Runs once a week
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - uses: actions/checkout@v3

    - name: Ensure we are not in login mode
      run: |
        # on caster or any pbs system, $PBS_ENVIRONMENT will give some informations about the job
        if [[ $PBS_ENVIRONMENT != "PBS_INTERACTIVE" && $PBS_ENVIRONMENT != "PBS_BATCH" ]]; then
          echo "::error::Workflow is running in login mode"
          exit 1
        else
          echo "Workflow is running in $PBS_ENVIRONMENT mode!"
          echo JobID = $PBS_JOBID
        fi

    - name: Navigate to directory and build with make
      run: |
        echo $LD_LIBRARY_PATH
        echo "Current directory:"
        echo $(pwd)
        module purge
        module load intel
        module load ncarcompilers
        module load openmpi
        module load cuda
        module load netcdf-mpi
        module load pnetcdf
        module load pio
        module list

        echo "Test build:"
        make clean CORE=atmosphere
        make pgi CORE=atmosphere PRECISION=single USE_PIO2=true
        echo "Build successful"

    #- name: Run Tests
      #run: |
        #echo "Running tests"
        #module purge
        # module load arm-forge
        #module load nvhpc
        #module load ncarcompilers
        #module load openmpi
        #module load cuda
        #module load netcdf-mpi
        #module load pnetcdf
        #module load pio
        #module list
        # codes for testing
        # echo "Every test passed successfully."
