# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-25T09:21:32+00:00
# Github: haniyeka

name: Check Dockerfile

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - .github/workflows/Dockerfile 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildContainer:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up community action Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: build and load docker image using community action Build Push action
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./docker/Dockerfile
        load: true
        tags: dockerimage:latest
    - name: echo
      run:
        echo "Dockerfile works!"
        nvc++ --version
