name: Dockerfile_workflow

  
on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - .github/workflows/Dockerfile 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildContainer:
    runs-on: docker
    container:
      image: docker/Dockerfile
    steps:
    - name: checkout
      uses: actions/checkout@v3
    #- name: set up community action Docker Buildx
    #  uses: docker/setup-buildx-action@v2
    #- name: build and load docker image using community action Build Push action
      #uses: docker/build-push-action@v2
      #with: 
      #  context: .
      #  file: ./docker/Dockerfile
      #  load: true
      #  tags: dockerimage:latest
    - name: check
      uses: ./.github/workflows/actions.yml
    - name: echo
      run:
        echo "Dockerfile works!"
