name: matrixMult_Fortran_Makefile

on: 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and make
      run: |
        cd Makefile/matrixMult/FORTRAN/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult
