name: matrixMult_CUDA

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/CUDA/** 
      - Autoconfig/matrixMult/CUDA/**
      - CMake/matrixMult/CUDA/**
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build_Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
    #container:
    #  image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3        
    - name: Navigate to directory and build with make
      run: |
        cd Makefile/matrixMult/CUDA/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult

  Build_Autoconf: 
    runs-on: [self-hosted, Linux, X64, casper]
    #container:
    #    #  image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3 
      - name: Navigate to directory and build with autoconfig
        run: |
          cd Autoconfig/matrixMult/CUDA/
          pwd
          autoconf
          ./configure
          make
          echo "Test Run:"
          ./matrix_mult

  Build_CMake:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - uses: actions/checkout@v3
    - name: Navigate to directory and build with cmake
      run: |
        cd CMake/matrixMult/CUDA/
        pwd
        mkdir build
        cd build
        cmake ..
        make
        echo "Test Run:"
        ./matrix_mult
