# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-24T19:51:32+00:00
# Github: haniyeka


name: matrixMult_OpenACC_Fortran

on:
  #schedule:
  #  - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/OpenACC_FORTRAN/**
      - Autoconfig/matrixMult/OpenACC_FORTRAN/**
      - CMake/matrixMult/OpenACC_FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build_Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
    #container:
    #  image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3        
    - name: Navigate to directory and build with make
      run: |
        cd Makefile/matrixMult/OpenACC_FORTRAN/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult
  
  Build_Autoconf:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Navigate to directory and build with autoconfig
      run: |
        cd Autoconfig/matrixMult/OpenACC_FORTRAN/
        pwd
        autoconf
        ./configure
        make
        echo "Test Run:"
        ./matrix_mult

  Build_CMake:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - uses: actions/checkout@v3
    - name: Navigate to directory and build with cmake
      run: |
        cd CMake/matrixMult/OpenACC_FORTRAN/
        pwd
        mkdir build
        cd build
        cmake ..
        make
        echo "Test Run:"
        ./matrix_mult
