name: matrixMult_OpenACC

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/OpenACC/** 
      - Autoconfig/matrixMult/OpenACC/**
      - CMake/matrixMult/OpenACC/**
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build_Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
    #container:
    #  image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3        
    - name: Navigate to directory and build with make
      run: |
        cd Makefile/matrixMult/OpenACC/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult

  Build_Autoconfig:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Navigate to directory and build with autoconfig
      run: |
        cd Autoconfig/matrixMult/OpenACC/
        pwd
        autoconf
        ./configure
        make
        echo "Test Run:"
        ./matrix_mult

  Build_CMake:
    runs-on: [self-hosted, Linux, X64, casper]
    steps:
    - uses: actions/checkout@v3
    - name: Navigate to directory and build with cmake
      run: |
        cd CMake/matrixMult/OpenACC/
        pwd
        mkdir build
        cd build
        cmake ..
        make
        echo "Test Run:"
        ./matrix_mult
