name: matrixMult_Fortran_Makefile

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.8.0-devel-ubuntu22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and make
      run: |
        cd Makefile/matrixMult/FORTRAN/ 
        pwd
        make

