name: matrixMult_Fortran_CMake

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - CMake/matrixMult/FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: haniyeka/cuda_mpi_container:5.0
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and do cmake
      run: |
        cd CMake/matrixMult/FORTRAN/ 
        pwd
        mkdir build
        cd build
        cmake ..
        make
        echo "Test Run:"
        ./matrix_mult
