name: matrixMult_Fortran_Makefile

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
      #container:
      #image: haniyeka/cuda_mpi_container:6.0
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and make
      run: |
        cd Makefile/matrixMult/FORTRAN/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult
