name: matrixMult_OpenACC_Fortran_Makefile

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/OpenACC_FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:
env: 
  IMAGE_NAME: dockerimage
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: $IMAGE_NAME:latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up community action Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: build and load docker image using community action Build Push action
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./docker/Dockerfile
        load: true
        tags: $IMAGE_NAME:latest
        
    - name: Navigate to directory and make
      run: |
        cd Makefile/matrixMult/OpenACC_FORTRAN/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult
