name: matrixMult_Fortran_Autoconfig

on: 
  schedule:
    - cron: '0 0 * * MON'
  push:
    branches: 
      - main
    paths: 
      - Autoconfig/matrixMult/FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and autoconfig
      run: |
        cd Autoconfig/matrixMult/FORTRAN/ 
        pwd
        autoconf
        ./configure
        make
        echo "Test Run:"
        ./matrix_mult
        
