name: matrixMult_OpenACC_Fortran_Makefile

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/OpenACC_FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda12.1-ubuntu22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3        
    - name: Navigate to directory and make
      run: |
        cd Makefile/matrixMult/OpenACC_FORTRAN/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult
