name: MPIStencil_MPI_CPU_Makefile

on:
  push:
    branches:
      - main
    paths: 
      - Makefile/MPIStencil/MPI/CPU/
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: ubuntu-latest
    container:
      image: haniyeka/cuda_mpi_container:5.0
    steps:
    - uses: actions/checkout@v3

    - name: Navigate to directory and make
      run: |
        echo $LD_LIBRARY_PATH
        cd Makefile/MPIStencil/MPI/CPU/
        pwd
        make
        echo "Test run:"
        ./MPIStencil
