name: MPIStencil_MPI_CPU_Autoconfig

on: 
  push:
    branches: 
      - main
    paths: 
      - Autoconfig/MPIStencil/MPI/CPU/ 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/nvhpc:23.5-runtime-cuda11.0-ubuntu22.04
    steps:
    - uses: actions/checkout@v3
      
    - name: Navigate to directory and autoconfig
      run: |
        cd Autoconfig/MPIStencil/MPI/CPU/ 
        pwd
        autoconf
        ./configure
        make
        echo "Test run:"
        ./MPIStencil
