name: MPIStencil_MPI_CPU_CMake

on: 
  push:
    branches: 
      - main
    paths: 
      - CMake/MPIStencil/MPI/CPU/
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
      #container:
      #image: haniyeka/cuda_mpi_container:6.0
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and do cmake
      run: |
        cd CMake/MPIStencil/MPI/CPU/ 
        pwd
        mkdir build
        cd build
        cmake ..
        make
        echo "Test run:"
        ./MPIStencil

