name: MPIStencil_MPI_CPU_CMake

on: 
  push:
    branches: 
      - main
    paths: 
      - CMake/MPIStencil/MPI/CPU/
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Makefile:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/nvhpc:22.9-devel-cuda11.7-ubuntu22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and do cmake
      run: |
        cd CMake/MPIStencil/MPI/CPU/ 
        pwd
        mkdir build
        cd build
        cmake ..
        make
        echo "Test run:"
        ./MPIStensil

