# Author: Haniye Kashgarani
# Affiliation: University of Wyoming
# ORCID: 0000-0001-6059-1920
# Date: 2023-07-24T19:51:32+00:00
# Github: haniyeka

name: simple_workflow_singularity

on:
  schedule:
    - cron: '0 0 * * MON' 
  push:
    branches: 
      - main
    paths: 
      - Makefile/matrixMult/FORTRAN/** 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_Makefile:
    runs-on: [self-hosted, Linux, X64, casper]
    #container:
    #  image: nvcr.io/nvidia/nvhpc:23.5-devel-cuda_multi-ubuntu22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Navigate to directory and build with make
      run: |
        cd Makefile/matrixMult/FORTRAN/ 
        pwd
        make
        echo "Test Run:"
        ./matrix_mult
